#!/usr/bin/env python3
"""Generate docs/TOOLS.md from the MCP tool definitions (names, parameters
and docstrings), so the reference never drifts from the code.

usage: scripts/gen_tool_docs.py [--check]
"""

import inspect
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
sys.path.insert(0, PKG)

from desmume_mcp import server  # noqa: E402

SECTIONS = [
    ("Session", r"^emu_(start|stop|status)$"),
    ("Emulation and input", r"^emu_"),
    ("Freeze dumps", r"^(freeze_dump|dump_)"),
    ("Debugger", r"^dbg_"),
    ("Memory", r"^mem_"),
    ("ROM", r"^rom_"),
    ("Labels", r"^label_"),
    ("Function analysis and labelling", r"^(func_list|func_info|nitro_scan)$"),
    ("Performance", r"^(perf_profile|func_hot)$"),
    ("Event hooks and 3D", r"^(hook_|gx_)"),
    ("Tracing: functions, assets, allocations, input", r"^(func_trace|asset_|alloc_|input_trace)"),
    ("Recording, replay and oracle tests", r"^(input_record|input_replay|oracle_)"),
]


def tools():
    out = []
    for name, fn in vars(server).items():
        fn = getattr(fn, "__wrapped__", None) and fn
        if callable(fn) and getattr(fn, "__wrapped__", None) and fn.__module__ == server.__name__:
            out.append((name, fn))
    return out


def signature(fn):
    parts = []
    for p in inspect.signature(fn).parameters.values():
        ann = p.annotation
        t = getattr(ann, "__name__", None) or str(ann).replace("typing.", "")
        t = t.replace(" | None", "?").replace("NoneType", "None")
        if p.default is inspect.Parameter.empty:
            parts.append(f"{p.name}: {t}")
        else:
            parts.append(f"{p.name}={p.default!r}")
    return ", ".join(parts)


def render():
    items = tools()
    lines = ["# MCP tool reference", "",
             "Generated by `scripts/gen_tool_docs.py` from the tool definitions in",
             "`desmume_mcp/server.py`. Addresses accept numbers, hex strings, labels",
             "(`player_update+0x10`) and registers (`sp+8`, `lr`).", ""]
    done = set()
    for title, pattern in SECTIONS:
        section = [(n, f) for n, f in items if re.match(pattern, n) and n not in done]
        if not section:
            continue
        lines += [f"## {title}", ""]
        for name, fn in section:
            done.add(name)
            doc = inspect.getdoc(fn) or ""
            lines += [f"### `{name}({signature(fn)})`", "", doc, ""]
    rest = [(n, f) for n, f in items if n not in done]
    if rest:
        lines += ["## Other", ""]
        for name, fn in rest:
            lines += [f"### `{name}({signature(fn)})`", "", inspect.getdoc(fn) or "", ""]
    lines.append(f"_{len(items)} tools._")
    return "\n".join(lines) + "\n"


def main():
    path = os.path.join(PKG, "docs", "TOOLS.md")
    text = render()
    if "--check" in sys.argv:
        current = open(path).read() if os.path.exists(path) else ""
        if current != text:
            print("docs/TOOLS.md is out of date, run scripts/gen_tool_docs.py")
            return 1
        return 0
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)
    print(f"wrote {path} ({len(tools())} tools)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
